### ISSUE TITLE
Downgrade compatibility

### ISSUE THREAD

**Issue by julien-leclercq** [MQuy/phoenix_mjml#1]
Phoenix 1.3 is really young and lot of apps won't make the transition for the moment. Your package should depend on phoenix ~> 1.2 imho, with maybe a bump of version in another version if you want to use new features.

**Comment by MQuy** [comment]
hi @julien-leclercq, nice suggestion. Can you help me to create a pr for this one? 👍🏻

**Comment by julien-leclercq** [comment]
https://github.com/ascential/phoenix_mjml

**Comment by julien-leclercq** [comment]
but i am looking into an other improvement, I think I'll push it during the week  or maybe monday :)

**Comment by MQuy** [comment]
@julien-leclercq, amazing. Cannot wait for it 👍🏻

**Comment by julien-leclercq** [comment]
https://github.com/MQuy/phoenix_mjml/pull/3
